// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift

import UIKit

struct Panna {
  struct Duplicate {
    var some: String 
  }
  
  struct Some {
    var some: String 
  }
  
  struct index {
    var data: data 
    var rs_msg: String 
    var rs_status: String 
    
    struct data {
      var cases:[ cases]
      var doctors:[ doctors]
      var slide:[ slide]
      var tags:[ tags]
      
      struct cases {
        var comments: String 
        var image: String 
        var name: String 
        var nid: String 
        var title: String 
        var views: String 
      }
      
      struct doctors {
        var avatar: String 
        var hname1: String 
        var hname2: String 
        var name: String 
        var tags:[ tags]
        var title: String 
        var uid: String 
        
        struct tags {
          var id: String 
          var name: String 
        }
      }
      
      struct slide {
        var fid: String 
        var image: String 
        var nid: String 
        var title: String 
        var type: String 
        var url: String 
      }
      
      struct tags {
        var id: String 
        var name: String 
      }
    }
  }
}